name: Build VSIX

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: Download artifact - win32
      id: download-win32
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-windows-x86_64\.zip'
        target: "./"
        regex: true
    - name: Download artifact - win-arm64
      id: download-win-arm64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-windows-aarch64\.zip'
        target: "./"
        regex: true
    - name: Download artifact - linux64
      id: download-linux64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-linux-x86_64\.zip'
        target: "./"
        regex: true
    
    - name: Download artifact - macos
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-macos-x86_64\.zip'
        target: "./"
        regex: true
    - name: Download artifact - macos-aarch64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-macos-aarch64\.zip'
        target: "./"
        regex: true
    - name: Copy Slang binaries and Build VSIX
      run: |
        export TAGNAME=${{ steps.download-win32.outputs.version}}
        export WIN32ZIP=slang-${TAGNAME:1}-win64.zip
        export WINARMZIP=slang-${TAGNAME:1}-win-arm64.zip
        export LINUX64ZIP=slang-${TAGNAME:1}-linux-x86_64.zip
        export MACOSX64ZIP=slang-${TAGNAME:1}-macos-x64.zip
        export MACOSAARCH64ZIP=slang-${TAGNAME:1}-macos-aarch64.zip
        source build-package.sh

        for file in ./*.vsix
        do
          echo "Built VSIX: $file"
        done
    - uses: actions/upload-artifact@v3
      with:
        name: slang-vsix
        path: |
          *.vsix